# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.8.3
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-10T13:38:44Z"
  labels:
    app: alpine-pod
  name: alpine-pod
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    - name: HOME
      value: /root
    - name: HOSTNAME
      value: 1ded7ea9d76d
    image: ghcr.io/linuxcontainers/alpine:latest
    name: alpine-podified

