# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.7.0
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-10-05T12:03:29Z"
  labels:
    app: httpd-pod
  name: httpd-pod
spec:
  containers:
  - env:
    - name: TERM
      value: xterm
    image: docker.io/library/httpd:latest
    name: httpd
    ports:
    - containerPort: 80
      hostPort: 9000
    stdin: true
    tty: true
