# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.7.0
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-10-05T13:38:09Z"
  labels:
    app: python-app-pod
  name: python-app-pod
spec:
  containers:
  - args:
    - run-redis
    env:
    - name: HOSTNAME
      value: 1a989b259fa9
    - name: TERM
      value: xterm
    image: quay.io/centos7/redis-5-centos7:latest
    name: redis
    ports:
    - containerPort: 5000
      hostPort: 5000
    - containerPort: 6379
      hostPort: 6379
    - containerPort: 8080
      hostPort: 8080
    securityContext:
      runAsNonRoot: true
    volumeMounts:
    - mountPath: /var/lib/redis/data
      name: e831e2e44dc3515f806e29690b9260a6c9f5ab3170ce78ac2c56626a2a67ebc2-pvc
  - env:
    - name: HOSTNAME
      value: 181d7e80ee1e
    - name: TERM
      value: xterm
    image: quay.io/slemeur/python-app:latest
    name: python
    securityContext:
      runAsNonRoot: true
  volumes:
  - name: e831e2e44dc3515f806e29690b9260a6c9f5ab3170ce78ac2c56626a2a67ebc2-pvc
    persistentVolumeClaim:
      claimName: e831e2e44dc3515f806e29690b9260a6c9f5ab3170ce78ac2c56626a2a67ebc2
