# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.5.0
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.podman.annotations.ulimit: nofile=1048576:1048576
  creationTimestamp: "2023-06-27T20:42:13Z"
  labels:
    app: httpd24-pod
  name: httpd24-pod
spec:
  containers:
  - args:
    - /usr/bin/run-httpd
    image: registry.access.redhat.com/ubi8/httpd-24:latest
    name: httpd24
    ports:
    - containerPort: 8080
      hostPort: 8080
    - containerPort: 8443
      hostPort: 8443
    securityContext:
      runAsNonRoot: true
    tty: true
